### PR TITLE
Add mirrored sourceforge documentation to make a GitHub Pages site

### PR DESCRIPTION
**Pull request by nopdotcom**
Note that this uses `/docs@master` as the GitHub Pages site, which does leave us with a confusing `doc` vs `docs` situation. Alternatively, you could create a `gh-pages` branch and just copy the files over from a checkout of this repo.

### CODE REVIEW

**Comment by pjz** [comment]
Maybe put it under `doc/html/` ?

**Comment by nopdotcom** [comment]
GitHub Pages insists on `/docs` if you want to store it in `master`. :‑(

**Comment by pjz** [comment]
Okay, so move doc to doc-src too maybe.  Is there a way to get the html generated from the tex instead of having to check it in?

**Comment by pjz** [comment]
Did this in a gh-pages branch instead.

**Pull request closed without merging**
